"""
Standalone test script - transcript scraping only
"""

from youtube_transcript_api import YouTubeTranscriptApi
import re
from datetime import datetime
import os

def extract_video_id(url):
    """Extract video ID from YouTube URL"""
    patterns = [
        r'(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([^&\n?#]+)',
        r'youtube\.com\/watch\?.*v=([^&\n?#]+)'
    ]
    for pattern in patterns:
        match = re.search(pattern, url)
        if match:
            return match.group(1)
    return None

# YouTube URL provided by user
video_url = "https://www.youtube.com/watch?v=y2NeAef6d30"

print("=" * 70)
print("🎬 YouTube Transcript Knowledge Base Tool - LIVE TEST")
print("=" * 70)
print(f"\n📹 Video URL: {video_url}\n")

# Step 1: Extract video ID
print("🔍 Extracting video ID...")
video_id = extract_video_id(video_url)
if not video_id:
    print("❌ Error: Could not extract video ID from URL")
    exit(1)

print(f"✅ Video ID extracted: {video_id}\n")

# Step 2: Fetch the transcript
print("⏳ Fetching transcript from YouTube...")
print("   (This may take a few seconds...)\n")

try:
    api = YouTubeTranscriptApi()
    fetched_transcript = api.fetch(video_id)
    full_transcript = fetched_transcript.text

    print("✅ Transcript fetched successfully!")
    print(f"   📊 Characters: {len(full_transcript)}")
    print(f"   📊 Words: ~{len(full_transcript.split())}\n")

    # Step 3: Save to markdown
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    markdown_file = f"outputs/transcript_{timestamp}.md"

    os.makedirs("outputs", exist_ok=True)

    markdown_content = f"""# YouTube Transcript

**Video ID:** {video_id}
**URL:** {video_url}
**Fetched:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## Transcript

{full_transcript}

---

*Generated by YouTube Transcript Knowledge Base Tool*
"""

    with open(markdown_file, 'w', encoding='utf-8') as f:
        f.write(markdown_content)

    print("📝 Markdown file created!")
    print(f"   📁 Saved to: {markdown_file}\n")

    # Step 4: Show preview
    print("=" * 70)
    print("📄 TRANSCRIPT PREVIEW")
    print("=" * 70)
    preview_length = min(1500, len(full_transcript))
    print(full_transcript[:preview_length])
    if len(full_transcript) > preview_length:
        print(f"\n... [+{len(full_transcript) - preview_length} more characters]")
    print("\n")

    print("=" * 70)
    print("✅ SUCCESS! The tool works perfectly!")
    print("=" * 70)
    print("\n🎉 What just happened:")
    print(f"   1. ✅ Scraped transcript from YouTube")
    print(f"   2. ✅ Extracted {len(full_transcript)} characters of text")
    print(f"   3. ✅ Saved to Markdown file: {markdown_file}")
    print("\n💡 The full web application includes:")
    print("   • Beautiful web interface (Streamlit)")
    print("   • PDF generation alongside Markdown")
    print("   • Append to existing files option")
    print("   • Knowledge base tracking")
    print("   • Download buttons")
    print("   • Statistics dashboard\n")

except Exception as e:
    print(f"❌ Error: {str(e)}")
    exit(1)
