"""
YouTube Transcript Scraper Module
Handles fetching transcripts from YouTube videos
"""

from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api._errors import TranscriptsDisabled, NoTranscriptFound
import re
from typing import Optional, Dict, List


def extract_video_id(url: str) -> Optional[str]:
    """
    Extract video ID from various YouTube URL formats

    Args:
        url: YouTube video URL

    Returns:
        Video ID or None if not found
    """
    patterns = [
        r'(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([^&\n?#]+)',
        r'youtube\.com\/watch\?.*v=([^&\n?#]+)'
    ]

    for pattern in patterns:
        match = re.search(pattern, url)
        if match:
            return match.group(1)

    return None


def get_video_transcript(video_url: str) -> Dict[str, any]:
    """
    Fetch transcript from YouTube video

    Args:
        video_url: YouTube video URL

    Returns:
        Dictionary containing transcript text, video_id, and status
    """
    video_id = extract_video_id(video_url)

    if not video_id:
        return {
            'success': False,
            'error': 'Invalid YouTube URL',
            'video_id': None,
            'transcript': None
        }

    try:
        transcript_list = YouTubeTranscriptApi.get_transcript(video_id)

        # Combine all transcript segments
        full_transcript = ' '.join([entry['text'] for entry in transcript_list])

        return {
            'success': True,
            'video_id': video_id,
            'transcript': full_transcript,
            'url': video_url,
            'error': None
        }

    except TranscriptsDisabled:
        return {
            'success': False,
            'error': 'Transcripts are disabled for this video',
            'video_id': video_id,
            'transcript': None
        }
    except NoTranscriptFound:
        return {
            'success': False,
            'error': 'No transcript found for this video',
            'video_id': video_id,
            'transcript': None
        }
    except Exception as e:
        return {
            'success': False,
            'error': f'Error fetching transcript: {str(e)}',
            'video_id': video_id,
            'transcript': None
        }


def format_transcript_for_markdown(transcript_data: Dict, title: str = None) -> str:
    """
    Format transcript data for markdown output

    Args:
        transcript_data: Dictionary containing transcript information
        title: Optional title for the transcript

    Returns:
        Formatted markdown string
    """
    video_id = transcript_data.get('video_id', 'Unknown')
    video_url = transcript_data.get('url', f'https://youtube.com/watch?v={video_id}')
    transcript = transcript_data.get('transcript', '')

    markdown_content = f"""# YouTube Transcript

**Video ID:** {video_id}
**URL:** {video_url}
{f"**Title:** {title}" if title else ""}

---

## Transcript

{transcript}

---

*Generated by YouTube Transcript Knowledge Base Tool*
"""

    return markdown_content
